[project]
name = "decentralized"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.trading]
path = "contracts/trading.clar"
depends_on = []
